### ISSUE TITLE
[BUG] Leveraging Bagging bug where input to drift detector is inverted.

### ISSUE THREAD

**Issue by RashidBakirov** [scikit-multiflow/scikit-multiflow#240]
**Describe the bug**
At line 287, the correct and incorrect classifications are reversed. At the moment, it is:
`add = 1 if (pred[0] == y_coded) else 0`
but should be:
`add = 0 if (pred[0] == y_coded) else 1`

In addition, while using Leverage Bagging with NaiveBayes base classifier, the reset of the classifier (line 305, `self.ensemble[i_max].reset()`) results in the deletion of class list and priors and the newly created (reset) classifier throws TypeError and returns 0 (line 375) while predicting. I have avoided this by calling partial_fit after reset, but not sure if this is the best practice.

**Comment by jacobmontiel** [comment]
Thanks for reporting this @RashidBakirov 

ADWIN input is indeed inverted. From preliminary tests, this seems to have an impact mainly when the `leveraging_bag_me` option is used. We will fix this.

The second bug regarding NaiveBayes is not clear to me. Can you share an MWE to replicate the error?

**Comment by RashidBakirov** [comment]
@jacobmontiel MWE for the second bug is a bit tricky, but you can do the following to replicate:
1) In leverage_bagging.py comment out line 243 `if change_detected:` and change line 246 `i_max = -1` to `i_max = 0`. This is done to force reset the classifier 0 in the ensemble for demonstration purposes.
2) Run the following script to see the described behaviour. You will see that `y_hat_nb` will be always 0, even if the 0 is not a valid class label. As oppopsed to this, HoeffdingTree works as expected and predicts either 1 or 2.
 
```
import numpy as np
from skmultiflow.meta import LeverageBagging
from skmultiflow.trees import HoeffdingTree
from skmultiflow.bayes import NaiveBayes

x=np.random.rand(10,2)
y=np.random.randint(2,size=10)+1
unique_targets = np.unique(y).tolist()

model_nb = LeverageBagging(base_estimator=NaiveBayes())
model_nb.partial_fit(x, y, classes=unique_targets)
y_hat_nb = model_nb.predict(x[0:1,:])
print("y_hat_nb=", y_hat_nb)

model_ht = LeverageBagging(base_estimator=HoeffdingTree())
model_ht.partial_fit(x, y, classes=unique_targets)
y_hat_ht = model_ht.predict(x[0:1,:])
print("y_hat_ht=", y_hat_ht)
```

**Comment by jacobmontiel** [comment]
Thanks @RashidBakirov, unfortunately, I am not able to reproduce the second error with the development version.

**Comment by RashidBakirov** [comment]
Perhaps this is already fixed in the dev version then, I am using the version 0.4.1 from pip.

**Comment by jacobmontiel** [comment]
Thanks for the clarification on the version. I went through the history of both methods and couldn't pinpoint a change that could relate to this. I will submit the fix for the first bug and will consider the second as non-reproducible.

**Comment by RashidBakirov** [comment]
Many thanks @jacobmontiel. 

For those who do encounter the second bug, I dug a bit in code, to see why after the change is detected, the prediction output is "correct" (in a sense that it is in allowed set of output labels) for HT base classifier and incorrect for NB. It turns out that after resetting the classifier in line 305 `self.ensemble[i_max].reset()` predicting using a reset (and not yet trained classifier) results in a single float value for NB. This throws error in line 398 `if len(partial_proba[0]) > max(self.classes) + 1:` as len() cannot be applied to float input. Thus, the prediction process is terminated, and 0 is returned as output. For HT however, the output from the reset classifier is an array, and thus there is no error thrown. 

To fix this issue, I have called partial_fit after resetting the classifier in line 305. I also think that this fix makes the code more in line with the original paper, as line 8 from Algorithm 2 suggests creating a new classifier right after the change is detected, which presumably involves training it with some data.

**Comment by jacobmontiel** [comment]
Thanks for the follow-up information. Although I still can't replicate the error in the development version the default value for `predict_proba` in `NaiveBayes` should be a 2d-array. I am adding this to the PR.

According to algorithm 2 in the original paper,  the current sample is used for training and then the model is monitored by ADWIN. If the model is replaced it should be trained on the next iteration.

![image](https://user-images.githubusercontent.com/17923265/81458122-f95aac80-91ec-11ea-8b32-b31ae14b1dfa.png) 

Although the mentioned workaround (`partial_fit` after resetting) helps, the current implementation is in alignment with the algorithm.

**Comment by RashidBakirov** [comment]
Great, thanks again for looking into that.
