### ISSUE TITLE
Meta models work with generated streams but give error for file streams

### ISSUE THREAD

**Issue by Bilgecelik** [scikit-multiflow/scikit-multiflow#41]
Hi, I use the same code of meta model for generated stream and it gives predictions but for file streams I receive an error.  Prequential evaluation gives 'NoneType' object is not iterable' error. When I code the evaluation myself, I see that the predictions for the csv file data streams are none type so 'corrects' are never increased and performance is 0.0.
The same file streams work with other classification methods.  Attached is one of the csv files I receive this error for. 

[CovPokElec.zip](https://github.com/scikit-multiflow/scikit-multiflow/files/2235849/CovPokElec.zip)

**Comment by jacobmontiel** [comment]
Hello @Bilgecelik, it seems that your file has an empty line after the header. This most likely is corrupting the stream during the data loading.

Could you confirm if removing the empty line solves the issue?

**Comment by Bilgecelik** [comment]
Hi, no it didn't but this error was there for all my csv files some of which don't include an empty line. Attached is the new version of covpokelec and another small file with no empty line but still gives the same error.
[Csv.zip](https://github.com/scikit-multiflow/scikit-multiflow/files/2235988/Csv.zip)

**Comment by jacobmontiel** [comment]
Thanks for confirming.

What meta-learners are giving you an error?

As a comment, we have addressed some bugs during the last days. Can you confirm that you have installed the last version of the framework?

**Comment by Bilgecelik** [comment]
OzaBagging, OzaBaggingADWIN, LeverageBagging are giving errors.
No I am using the version before the structure update because import functions were giving the following error for meta models in the new version:
ModuleNotFoundError: No module named 'libNearestNeighbor'
I can also open an issue for that.

**Comment by jacobmontiel** [comment]
I can confirm that the meta-algorithms are working on the latest version:

![covpokelec](https://user-images.githubusercontent.com/17923265/43342321-9a36c7e0-91e2-11e8-860c-1b7c4a3e2422.png)
![ripley_synth](https://user-images.githubusercontent.com/17923265/43342322-9a580c48-91e2-11e8-96b3-2b7d1d95139f.png)

---

Regarding the error, 'libNearestNeighbor' was moved during the structure update. You need to run the setup again in order for it to work. Let me know if you have issues installing the latest version.

**Comment by Bilgecelik** [comment]
Hi Jacob, it is great to see that new version is working but I receive this error installing:
![image](https://user-images.githubusercontent.com/38037323/43405792-f1f300a4-941a-11e8-83b0-e3fcddb02523.png)
So 'libNearestNeighbor' is still an issue for me at least. Any recommendations how to solve it?
Thanks!

**Comment by jacobmontiel** [comment]
That is strange, the path corresponds to the new structure, so it seems like an issue with your project update. My suggestion would be to download again the whole project to make sure you have everything up to date.

**Comment by Bilgecelik** [comment]
I reinstalled and it is working now, meta models are also working. Thanks for the help!
